<?php
return array('primary_route' => array('slug' => 'users', 'type' => 'map', 'action' => 'User\Users'),
			 'routes' 		 => array('invite' => array('type' 	=> 'map',
														'route' => 'invite',
														'action'=> 'User\Invite',),
									  'invite/resend/@id' => array('type'  => 'GET',
																   'route' => 'invite/resend/@id',
																   'action'=> 'User\Invite->resend',),
									  'invite/delete/@id' => array('type'  => 'GET',
															  'route' => 'invite/delete/@id',
															  'action'=> 'User\Invite->delete',),					
									  'invite-check' => array('type'  => 'POST',
															  'route' => 'invite-check',
															  'action'=> 'User\Invite->checkinviteexists',),
									  'invite-complete' => array('type' 	=> 'GET',
																 'route' 	=> 'invite-complete', 		
																 'action'	=> 'User\Invite->complete',),
									  'user' => array('type' 	=> 'map',
													  'route' 	=> 'user', 	
													  'action'	=> 'User\User',),
									  'user/@id' => array('type' 	=> 'map',
														  'route' 	=> 'user/@id', 		
														  'action'	=> 'User\User',),
									   'user/delete/@id' => array('type' 	=> 'GET',
																  'route' 	=> 'user/delete/@id', 		
																  'action'	=> 'User\User->delete',),),
			 'submenus'		 => array('users'  => 'List users',
									  'user'	  => 'Add user'));
?>