<?php
return array('primary_route' => array('slug' => 'product', 'type' => 'map', 'action' => 'Product\Product'),
			 'routes' 		 => array('@id'		 => array('type' 	=> 'map',
														  'route' => '@id',
														  'action'=> 'Product\PFile',),						  
									  'delete/@id'		 => array('type' 	=> 'GET',
																  'route' => 'delete/@id',
																  'action'=> 'Product\Product->delete',),
									  'undelete/@id'		 => array('type' 	=> 'GET',
																      'route' => 'undelete/@id',
																	  'action'=> 'Product\Product->undelete',),
									  'modaladd'	 => array('type' 	=> 'GET',
																  'route' => 'modaladd [ajax]',
																  'action'=> 'Product\Product->loadModalAdd',),
									  'modalimport'	 => array('type' => 'GET',
															  'route' => 'modalimport [ajax]',
															  'action'=> 'Product\Product->loadModalImport',),
									  'import'	 => array('type' 	=> 'POST',
														  'route' => 'import [ajax]',
														  'action'=> 'Product\Product->import',),
									  'searchjson'	 => array('type' 	=> 'GET',
														  'route' => 'searchjson [ajax]',
														  'action'=> 'Product\Product->searchjson',),
									  'searchjsonstock'	 => array('type' 	=> 'GET',
														  'route' => 'searchjsonstock [ajax]',
														  'action'=> 'Product\Product->searchjsonstock',),
									   'jsondata/@id'	 => array('type' 	=> 'GET',
																  'route' => 'jsondata/@id [ajax]',
																  'action'=> 'Product\Product->jsondata',),
										'category'	 => array('type' 	=> 'map',
																  'route' => 'category',
																  'action'=> 'Product\Category',),
										'category/@id' => array('type' 	=> 'GET',
																'route' => 'category/@id [ajax]', 		
																'action'=> 'Product\Category->view',),
										'category/delete/@id' => array('type' 	=> 'GET',
																	   'route' => 'category/delete/@id', 		
																	   'action'=> 'Product\Category->delete',),),
		 'submenus'		 => array('product'  => 'Produse',
								  'category' => 'Categorii'));
?>