<?php
return array('primary_route' => array('slug' => 'produse', 'type' => 'map', 'action' => 'Produse\Produse'),
			 'routes' 		 => array('delete/@id' => array('type' 	=> 'GET',
														   'route' => 'delete/@id',
														   'action'=> 'Produs\Produs->delete',),
									  'produs/irevision/@id' => array('type' 	=> 'GET',
														   'route' => 'produs/irevision/@id [ajax]',
														   'action'=> 'Produse\Produs->irevision',),
									  'quick-view/@id' => array('type' 	=> 'GET',
															   'route' => 'quick-view/@id [ajax]',
															   'action'=> 'Produse\Produs->loadQuickViewTemplate',),
									  'produs' => array('type' 	=> 'map',
														'route' => 'produs',
														 'action'=> 'Produse\Produs',),					   
									  'produs/@id' => array('type' 	=> 'GET',
															'route' => 'produs/@id',
														    'action'=> 'Produse\Produs->get',),
									  'produs/status/@id' => array('type' 	=> 'GET',
															'route' => 'produs/status/@id',
														    'action'=> 'Produse\Produs->delete',),
									  					
									  'subprodusadd/@sapid' => array('type' 	=> 'GET',
															   'route' => 'subprodusadd/@sapid [ajax]',
															   'action'=> 'Produse\Produs->getSubProdusTemplate',),
									  'subprodusadd' => array('type' 	=> 'POST',
																			'route' => 'subprodusadd [ajax]',
																			'action'=> 'Produse\Produs->setSubProdus',),
									  'subprodusdel/@id' => array('type' 	=> 'GET',
																  'route' => 'subprodusdel/@id [ajax]',
																  'action'=> 'Produse\Produs->delSubProdus',),
									  'cart'			 => array('type' 	=> 'map',
																  'route' => 'cart',
																  'action'=> 'Produse\Cart',),
									  'cartadd/@id'			 => array('type' 	=> 'GET',
																  'route' => 'cartadd/@id [ajax]',
																  'action'=> 'Produse\Cart->addToCart',),
									  'cartreload'			 => array('type' 	=> 'GET',
																  'route' => 'cartreload [ajax]',
																  'action'=> 'Produse\Cart->showcart',), 
									  'cartdelete/@id'			 => array('type' 	=> 'GET',
																  'route' => 'cartdelete/@id',
																  'action'=> 'Produse\Cart->delete',),
									   'cartempty'			 => array('type' 	=> 'GET',
																  'route' => 'cartempty',
																  'action'=> 'Produse\Cart->emptycart',),
									));
?>